# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\x11inventory_service\"Q\n\rInventoryItem\x12\x14\n\x0cproduct_code\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x05\x12\x0c\n\x04\x63ost\x18\x04 \x01(\x01\"(\n\x10InventoryRequest\x12\x14\n\x0cproduct_code\x18\x01 \x01(\t\"%\n\x11InventoryResponse\x12\x10\n\x08response\x18\x01 \x01(\t2\xa7\x02\n\x10InventoryService\x12U\n\x0cGetInventory\x12#.inventory_service.InventoryRequest\x1a .inventory_service.InventoryItem\x12Z\n\x10\x41\x64\x64InventoryItem\x12 .inventory_service.InventoryItem\x1a$.inventory_service.InventoryResponse\x12`\n\x13\x44\x65leteInventoryItem\x12#.inventory_service.InventoryRequest\x1a$.inventory_service.InventoryResponseB\tZ\x07./protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\007./proto'
  _globals['_INVENTORYITEM']._serialized_start=38
  _globals['_INVENTORYITEM']._serialized_end=119
  _globals['_INVENTORYREQUEST']._serialized_start=121
  _globals['_INVENTORYREQUEST']._serialized_end=161
  _globals['_INVENTORYRESPONSE']._serialized_start=163
  _globals['_INVENTORYRESPONSE']._serialized_end=200
  _globals['_INVENTORYSERVICE']._serialized_start=203
  _globals['_INVENTORYSERVICE']._serialized_end=498
# @@protoc_insertion_point(module_scope)
